plaid/plaid-ruby

- lib/plaid/config.rb
- spec/config_spec.rb
> Add trailing slash to environment_location if missing

- README.md
- lib/plaid.rb
- lib/plaid/connection.rb
- lib/plaid/models/exchange_token_response.rb
- spec/plaid_spec.rb
Closes https://github.com/plaid/plaid-ruby/issues/53.
> Add /exchange_token endpoint

- lib/plaid/models/institution.rb
- spec/institution_spec.rb
Parse products in the institution model
> Institution Products List support

- PUBLISHING.md
For https://github.com/plaid/plaid-ruby/issues/66
> Adding PUBLISHING.md

- lib/plaid/user.rb
- test/test_user.rb
Wrap a `PATCH /connect` request. A similar thing was discussed in #101.
> User#update_webhook

- README.md
- lib/plaid/user.rb
- test/fixtures/exchange_token.json
- test/test_user.rb
> Support stripe_bank_account_token in User.exchange_token

- README.md
> Use :production in README as well

- lib/plaid/transaction.rb
Fix typo in to_s should display account id
> to_s to show account id

- lib/plaid/user.rb
- test/test_user.rb
If `User#update` returns an MFA response, `User#mfa_step` will use `PATCH /:product/step`, not
`POST`.
Resolves #129
> Implement PATCH /:product/step flow

- README.md
- lib/plaid.rb
- lib/plaid/webhook.rb
We wanted to interact with received Webhook events in an object oriented way, so we modeled the Webhook object.
> Added Webhook object

- lib/plaid/connector.rb
- test/test_connector.rb
> Raise ServerError in case of empty body

- lib/plaid/webhook.rb
- test/test_webhook.rb
Also add missing tests. Fixes #143
> Fix off-by-one bug in Plaid::Webhook

- LICENSE.txt
Might need to do this for the other client libraries, too.
> Adding company name to license

- README.md
Raised via https://github.com/plaid/plaid-ruby/issues/163.
> readme: fix url

- .env.sample
- .gitignore
- Rakefile
- plaid.gemspec
Hey! Here's a PR that implements some suggestions I had. Cheers! 🍻
> Add dotenv

- Rakefile
Otherwise `rake update_gh_pages` didn't work.
> Add missing require to Rakefile

- lib/plaid/products/sandbox.rb
- test/test_item.rb
- test/vcr_cassettes/PlaidItemTest_test_public_token_sandbox.yml
endpoint: /sandbox/public_token/create
> add sandbox-only endpoint

- lib/plaid/models.rb
- lib/plaid/products/institutions.rb
- test/test_institutions.rb
- test/vcr_cassettes/PlaidInstitutionsTest_test_get_by_id_include_institution_data.yml
- test/vcr_cassettes/PlaidInstitutionsTest_test_get_by_id_with_include_institution_data.yml
- test/vcr_cassettes/PlaidInstitutionsTest_test_get_with_include_institution_data.yml
- test/vcr_cassettes/PlaidInstitutionsTest_test_get_with_options.yml
- test/vcr_cassettes/PlaidInstitutionsTest_test_search_with_include_institution_data.yml
- test/vcr_cassettes/PlaidInstitutionsTest_test_search_with_institution_data.yml
This flag is supported for the following endpoints:
/institutions/search
/institutions/get
/institutions/get_by_id
> Add support for include_institution_data flag

- lib/plaid.rb
- lib/plaid/client.rb
- lib/plaid/models.rb
- lib/plaid/products/liabilities.rb
- test/test_liabilities.rb
- test/vcr_cassettes/PlaidLiabilitiesTest_test_get.yml
- test/vcr_cassettes/PlaidLiabilitiesTest_test_get_invalid_access_token.yml
Adds a wrapper for /liabilities/get.
> Add support for liabilities product

- lib/plaid.rb
- lib/plaid/client.rb
- lib/plaid/models.rb
- lib/plaid/products/payment_initiation.rb
- test/test_payment_initiation.rb
- test/vcr_cassettes/PlaidPaymentInitiationTest_test_all_routes.yml
Implements UK payment initiation client library
> Implements UK payment initiation client library

- CHANGELOG.md
- Gemfile.lock
- lib/plaid/version.rb
Prepares changelog and file changes for v8.4.0
> Prepares changelog and file changes for v8.4.0

- lib/plaid.rb
- lib/plaid/client.rb
- lib/plaid/models.rb
- lib/plaid/products/webhooks.rb
- test/test_webhooks.rb
- test/vcr_cassettes/PlaidWebhooksTest_test_get_verification_key.yml
Add `/webhook_verification_key/get` endpoint to plaid-ruby
> Add /webhook_verification_key/get endpoint

- lib/plaid/products/item.rb
- test/test_item.rb
- test/vcr_cassettes/PlaidItemTest_test_add_token_create.yml
(todo) tests will pass once this field in available on our API
> Support passing user field to /item/add_token/create

- PUBLISH.md
Add instructions for setting up rubygems authentication and MFA settings
> Clarify publish instructions

- README.md
related issue : https://github.com/plaid/plaid-ruby/issues/298
I used wording from your official page which showcases a Nodejs server https://plaid.com/docs/#integrating-with-link
> Update Readme with link token creation example

- Gemfile.lock
- lib/plaid/products/institutions.rb
- test/test_institutions.rb
- test/vcr_cassettes/PlaidInstitutionsTest_test_get.yml
- test/vcr_cassettes/PlaidInstitutionsTest_test_get_by_id.yml
- test/vcr_cassettes/PlaidInstitutionsTest_test_get_by_id_include_optional_metadata.yml
- test/vcr_cassettes/PlaidInstitutionsTest_test_get_by_id_include_status_false.yml
- test/vcr_cassettes/PlaidInstitutionsTest_test_get_by_id_invalid_parameters.yml
- test/vcr_cassettes/PlaidInstitutionsTest_test_get_invalid_parameters.yml
- test/vcr_cassettes/PlaidInstitutionsTest_test_get_with_options.yml
- test/vcr_cassettes/PlaidInstitutionsTest_test_search.yml
- test/vcr_cassettes/PlaidInstitutionsTest_test_search_bad_products.yml
- test/vcr_cassettes/PlaidInstitutionsTest_test_search_invalid_products.yml
- test/vcr_cassettes/PlaidInstitutionsTest_test_search_with_include_optional_metadata.yml
- test/vcr_cassettes/PlaidInstitutionsTest_test_search_with_products.yml
Country codes are now required for the /institutions/ API endpoints. This updates the client library to properly take a country_codes field
> Add country codes to institutions/ routes

- Gemfile.lock
- lib/plaid/models.rb
- lib/plaid/products/payment_initiation.rb
- test/test_payment_initiation.rb
- test/vcr_cassettes/PlaidPaymentInitiationTest_test_all_routes.yml
Supports creating Standing Orders through this client library
> Add Standing Order support to Payment Initiation

- lib/plaid/models.rb
- test/test_helper.rb
- test/test_institutions.rb
- test/test_payment_initiation.rb
- test/vcr_cassettes/PlaidInstitutionsTest_test_get_by_id_include_payment_initiation_metadata.yml
Adds payment_initiation metadata support. We are returning some more information in the institutions endpoints response.
> Adds payment_initiation metadata support

- CHANGELOG.md
- Gemfile.lock
- lib/plaid/version.rb
Update changelog for version 13.1.0
> 13.1.0 changelog

- lib/plaid/models.rb
- lib/plaid/products/payment_initiation.rb
- test/test_payment_initiation.rb
- test/vcr_cassettes/PlaidPaymentInitiationTest_test_payment_with_bacs_options.yml
- test/vcr_cassettes/PlaidPaymentInitiationTest_test_payment_with_iban_options.yml
Adds ability to pass an options hash as an argument to create payment.
> Adds support for new payment initiation options
