lib/plaid.rb
lib/plaid/models/transaction.rb
spec/plaid_spec.rb
spec/transaction_spec.rb

API: public
`Plaid.transactions` lets you query `/connect/get` with options. Pass it an access-token along with the options. This is intended for use with webhooks, so you can query a subset of transactions when notified by a webhook.
Examples:
```
Plaid.transactions 'test_wells'
Plaid.transactions 'test_wells', account: "XARE85EJqKsjxLp6XR8ocg8VakrkXpTXmRdOo"
Plaid.transactions 'test_wells', pending: true
Plaid.transactions 'test_wells', account: "XARE85EJqKsjxLp6XR8ocg8VakrkXpTXmRdOo", gte: "2014-07-24", lte: "2014-07-25"
```
Additionally: added `date` to `Plaid::Transaction`

Plaid.transactions

---

lib/plaid/models/account.rb
spec/account_spec.rb

The results returned by Plaid allows you to distinguish between a checkings or a savings account via the `subtype` field. However, this is not available in the test data at the current date. This patch adds code to make `subtype` available to `Plaid::Account` objects.

Added "subtype" for Account

---

README.md
lib/plaid/version.rb

The 1.5.1 release includes https://github.com/plaid/plaid-ruby/pull/59.

plaid-ruby@1.5.1

---

plaid.gemspec

No sense locking people to 2.1.3+ if it's not needed.
(FWIW, I tried dropping it down to 1.9, but the specs failed.)

Reducing required Ruby version

---

README.md

Example Plaid.set_user('access_token', 'wells') is incorrect. Array with auth levels should be passed instead.

Fixed invalid code example

---

lib/plaid.rb
lib/plaid/connection.rb
lib/plaid/errors.rb
plaid.gemspec
spec/connection_spec.rb
spec/plaid_error_spec.rb
spec/plaid_spec.rb
spec/spec_helper.rb

I wanted clearer exceptions and access to the code/message that the API was handing back to me, and unfortunately, api_res didn't seem to cover all the use cases.  I created a PlaidError which encapsulated the data I wanted from the request. Another thing I could do, is actually just jam the json object in there and let anyone access the full response from the api on error (sometimes very useful). This also helps refactor out the "error_handler" function, which seemed like a good benefit. 
This gives me the freedom to catch a particular exception, and cleanup according to the api response code that you guys use. Since your api is pretty sweet and has so many various states that an account can be in, this is essential for someone like me to create a robust ruby app with. I've updated the …

Clearer Exception Handling for the client user

---

lib/plaid/connection.rb
plaid.gemspec

Support added for ruby 1.9.3
Successfully executed specs both in 1.9.3 & 2.2.0
=> ruby-2.2.0 [ i686 ]
Finished in 1 minute 54.09 seconds (files took 0.31953 seconds to load)
122 examples, 0 failures, 4 pending
=* ruby-1.9.3-p551 [ i686 ]
Finished in 2 minutes 23.5 seconds (files took 0.37978 seconds to load)
122 examples, 0 failures, 4 pending

Support added for ruby 1.9.3

---

.rspec
README.md
lib/plaid.rb
lib/plaid/models/transaction.rb
lib/plaid/models/user.rb
spec/account_spec.rb
spec/category_spec.rb
spec/config_spec.rb
spec/connection_spec.rb
spec/institution_spec.rb
spec/plaid_error_spec.rb
spec/plaid_spec.rb
spec/transaction_spec.rb
spec/user_spec.rb

1) readme wording improvements
2) rspec imports simplified by using `.rspec`. bonus: now it has colors
3) remove unnecessary `return` operators
4) fix attr_accessor assignment in `Transaction` class
5) few spec example description improvements according to http://betterspecs.org/ suggestions

wording improvements and some ruby fixes

---

lib/plaid/connection.rb
lib/plaid/version.rb
spec/connection_spec.rb

This is very unlikely when using tartan or production, but when using Plaid's internal development/testing environments this happens occasionally.
This is an attempt to handle this case gracefully, instead of raising a `JSON::ParserError` exception.
c.p. https://stackoverflow.com/questions/8390256/a-json-text-must-at-least-contain-two-octets

Handling an empty response from the server.

---

lib/plaid/models/user.rb

For https://github.com/plaid/plaid-ruby/issues/82.
Basically this will ensure new accounts are only added to the user if there is no current account with the same id.

Skip adding accounts if they already exist.

---

lib/plaid/models/account.rb
spec/account_spec.rb

https://plaid.com/docs/#data-overview
We can see from the docs that there is no "name" attribute, but that the name is found under "meta.name". The current API responses match the documentation.

Fix Account#name to use the right hash key

---

lib/plaid/models/user.rb

If a response with MFA is received, it's a hash, so for data consistency, it's important to use an empty hash instead of a string if no MFA exists.

User: set pending_mfa_questions to hash

---

.travis.yml
README.md
lib/plaid.rb
lib/plaid/models/exchange_token_response.rb
lib/plaid/version.rb
spec/plaid_spec.rb

The `/exchange_token` endpoint now takes two parameters.
cc @michaelckelly

Updating exchange_token method to reflect API changes

---

README.md
lib/plaid/user.rb
test/test_user.rb

Not sure what happened with that last PR... Anyway, to recap:
The send_method parameter needs to go into the options field according to the Plaid docs. Also, there was no access to the options param for adding things like login_only and webhook so I added an extra argument for it. And a minor readme typo fix. And as an aside, I couldn't decide whether to merge the send_method param into options, so I just left it as two parameters in case it would break some reliance on send_method in the rest of the code/tests.

User#mfa_step signature change and minor readme update

---

lib/plaid/client.rb
test/test_client.rb
test/test_config.rb

`:api` was replaced with `:production`.

Support :production in Plaid::Client#env=

---

plaid.gemspec

Using `~> 1.0` per [multi_json README](https://github.com/intridea/multi_json#versioning).
Resolves #117

Relax multi_json version dependency

---

lib/plaid/transaction.rb
test/test_transaction.rb

Adds support for _reference_number, a transaction field specified in https://plaid.com/docs/api/#data-overview

Add _reference_number to Transaction class

---

lib/plaid/products/institutions.rb
test/test_institutions.rb

According to the [documentation](https://plaid.com/docs/api/#all-institutions), this feature should be supported. However, in practice, it's not.
I have added the extra `options` keyword argument to the `institutions#get` method, as well as modified the test case to include the extra argument.

Implement the options parameter for institutions#get

---

lib/plaid/products/processor.rb
test/test_processor.rb
test/vcr_cassettes/PlaidProcessorTest_test_ocrolus_processor_token_create_invalid_account_id.yml

Adds a new product class for Ocrolus processor tokens. Code and tests are more or less copypasted from what already exists for other processors.
Once we need to add more of these it'll probably be worth refactoring this a bit more to DRY it out.
~Also, this failed a CI test because the Assets model hadn't been updated to use the new `postal_code` `region` and `country` address fields. Our API changelog mentions this change being made for Identity and Transactions responses; is this a problem? And should I open a separate PR for this change, since it's out of the PR's original scope?~ ~Whoops, just saw https://github.com/plaid/plaid-ruby/pull/236. Should I roll my own address fields change back and wait for 236 to be merged in?~
Now that #236 has been merged, I got rid of the commit where …

Add support for Ocrolus as a processor

---

lib/plaid/models.rb
test/test_institutions.rb

If there is not enough traffic to accurately calculate institution status, as is the case in the sandbox environment, the API returns null rather than potentially inaccurate data, so the status test no longer works.

Fix PlaidInstitutionsTest, PlaidInvestmentsTest, and PlaidTransactionsTest

---

lib/plaid/models.rb
test/test_transactions.rb
test/vcr_cassettes/PlaidInstitutionsTest_test_get.yml
test/vcr_cassettes/PlaidInstitutionsTest_test_get_by_id.yml
test/vcr_cassettes/PlaidInstitutionsTest_test_get_by_id_include_optional_metadata.yml
test/vcr_cassettes/PlaidInstitutionsTest_test_get_by_id_include_status.yml
test/vcr_cassettes/PlaidInstitutionsTest_test_get_by_id_include_status_false.yml
test/vcr_cassettes/PlaidInstitutionsTest_test_get_with_options.yml
test/vcr_cassettes/PlaidInstitutionsTest_test_search.yml
test/vcr_cassettes/PlaidInstitutionsTest_test_search_with_include_optional_metadata.yml
test/vcr_cassettes/PlaidInstitutionsTest_test_search_with_products.yml

Adds a new `oauth` field to the institution schema returned by `/institutions/get`, `/institutions/get_by_id`, and `/institutions/search`. No changes are necessary to support the new `oauth` request option for `/institutions/get` and `/institutions/search`.

Add OAuth support to /institutions endpoints

---

lib/plaid/products/sandbox.rb

method to set verification status on an item from the AMD flow
tested manually with
```
require_relative 'Plaid'
client = Plaid::Client.new(env: :sandbox,
client_id: '...',
secret: '...',
public_key: '...')
resp = client.sandbox.sandbox_item.set_verification_status('...', 'GMxydz6kM4tDdrPJBwPXiPzQ7Pwabaf1oq84a', 'verification_expired')
print(resp)

set verification status

---

Gemfile.lock

When running `bundle`, this diff is created. I assume someone forgot to commit it in a previous PR?

Commit gemfile lock changes

---

lib/plaid/errors.rb

This PR fixes the error type mapping for the `Plaid::RateLimitExceededError`. As seen in the [plaid docs](plaid.com/docs/#rate-limit-exceeded-errors), the `error_type` in the response is actually `"RATE_LIMIT_EXCEEDED"` not `"RATE_LIMIT_EXCEEDED_ERROR"`

Fix error type mapping for RateLimitExceededError

---

lib/plaid/models.rb
test/test_liabilities.rb
test/vcr_cassettes/PlaidLiabilitiesTest_test_get.yml
test/vcr_cassettes/PlaidLiabilitiesTest_test_get_invalid_access_token.yml

Adds the credit card liability type to the liabilities product: https://plaid.com/docs/#credit-card-liability-schema
Note that I changed the test item institution because the sandbox institution seems to return a credit card liability object with an incorrect schema. It contains an undocumented property `last_statement_date` instead of the documented `last_statement_issue_date`. In prod and in a non sandbox institution, the correctly formatted object is returned. Guessing that needs to be fixed by Plaid.

add support for credit card liabilities

---

README.md

This almost tripped me up. Not entirely sure if this is correct, but looks like it from the changelog. I got confused into thinking version 11 wasn't a final release yet.

Add missing versions to API version support table

---

lib/plaid/products/item.rb
lib/plaid/products/payment_initiation.rb
test/test_item.rb
test/test_payment_initiation.rb

Add back support for the legacy token create endpoints but mark them as deprecated since we advice new client library users from using them. They will be supported in this version but will eventually be eventually be removed for real in some future version.
/item/public_token/create
/item/add_token/create
/payment_initiation/payment/token/create

add back legacy token endpoints

---

CHANGELOG.md
Gemfile.lock
README.md
lib/plaid/models.rb
lib/plaid/version.rb
test/test_payment_initiation.rb
test/test_processor.rb

Add maintenance warning.
Tests to Pass:
- Income + Credit test deprecation.
- Add `update_type` to `Item`.
- Fixed a couple flaky processor tests. Needed their stubs updated too.
Version update needed to be published here.

Maintenance warning

---

CHANGELOG.md
Gemfile.lock
Makefile
lib/plaid/models/paystub.rb
lib/plaid/version.rb

Manually change IncomeBreakdown to Array<IncomeBreakdown> in the Paystub class.
*This change was not auto-generated and will only be available on this release and Gem versions >=14.1.0*
This is to fix an issue in `14.0.0.beta.5` and will be released as `14.0.0.beta.5-plural-income-breakdown`

Manually change IncomeBreakdown to Array<IncomeBreakdown>
